dist: xenial
sudo: required
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "zpajNdcnp1vqUvgUl78T07MC0vc9Cu1UFYI3sC9xIyAXxQh4NEb67NBqmSSNtr5+oOn+m22SVSS1VkgUwmIkf7FmR
cV2/vRE7qBXKHmO9W+BrC2FucKSL2aTeqwIpirTLMkkZlMp8/8TAtFQnHt7o7YfEtvhlVTtQGZzIRQbUQBu6Btyv7+QLmuGa5xOD
iSP4BPbU+SZcw5sKVadoN/8mFDYKG7B0a9+807JsMMzGA4cGgnrCSis3ErnkD9VP/WASR0vJaZCSAAzx5bJdL7yuYpjKL91NhU90
L9PcOBByTHEBCYSSuAOnRZrRzaKEwirauJi9HmW4zK+OctK9YF+NzU1V3aiT0HN8PQd1Q2oXes7sgLzvlJFJFJNCLyCSLKYrqHrM
4KbzQ96B1iOQdQVMVxFUFWp4VoS+/frsb2kMXw7QRUIY7AluHUhFTZBnauVc89xBW8lE0TG+nr/i8rLt2aTmVek2ocw3Uq0zohAl
wiXvs1t+Z8YuRWEwitIPQiF37mdXwh477m3VwR8pAYg8cWS5tL3dNwd1EUi8tf0j54dW6URoJhgo89bVZmjBXPrgiIVZvXevkhMt
owBPuMOSWle51aeWCk5vLBCALYJVryUkQhWV/xLH44RIbZxSIh0ki3rRu9wt8sCo1QyjLW26opwFyxv4OGbbJcUlfKdAjg="

addons:
  sonarcloud:
    organization: "phax-github"
    token:
      secure: "1qHC8PPpoMjI3HLoHBX/Z3JaPjDo4h4+4j1YOnJ76OD9DMDyg7MvykHfxWulWdtxgFJOeVeKHL8syeB8wQqofpuBTSlf/xiaEDjK2jbDk9Y1m4z3/HcB1XlHU4YR2Fa27EDkiYlfXhjqV5RjRLpym
fiJ23HD/xmrmVZbZKDxjW/A0iwzscIxQ9hS00xS+4PBj39eePTvpsek8i2aks2m4vIi+h/XHP7nv5BLnm13rLt8+IHPB+9kF/HOG1WTOymCG71OR8uPCFZqm3Gj92zMFHhCX29TCEd4u6XqIOVVNwvg5cjUaXShX
KMyYjPYhLpjrJqBkRwRxI2X/j0ss827DVniqoAstCgS1I9zWCugfbCvKuiVHFiMSME+jS/SPdikMkipy45VshZAgQFsEFg/1BDwG9GGCRuUVF00ZmHYaCX4WALDfrIlXu6qSWcPYvCOZkNkD8TqfWUdSgfUCTQiy
tR3hSVhqGgKKSJYlFQlfpN2Hz7Ikqf9oOJKHeBfuszKn/O8GTgv+E0u3ZqPUWGclfD/z4FNr0m+eup61D92ErwXVM5ITWFwknHrfRVb5Vh1LzsDAKjdwA6JpAxLghABhJ2IHnXzeghcj6EQXp9agCUwNhy0Gn1cr
3Md5qFAAmoQTqcj736cZkklFMo3V42+8vzQMFmnJRW4Ss4UjGiEJ2w="

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B -P coverage sonar:sonar
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk14
      script:
        - mvn test -B
